/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AppSettings {
  'appName' : string,
  'logo' : [] | [ExternalBlob],
}
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export interface CustomerOffer {
  'id' : string,
  'customerName' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'customerId' : Principal,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FounderOffer {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'productId' : [] | [string],
  'discount' : bigint,
  'image' : [] | [ExternalBlob],
}
export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'customerId' : Principal,
  'items' : Array<ProductOrderItem>,
  'customerEmail' : string,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'founderId' : Principal,
  'category' : ProductCategory,
  'image' : [] | [ExternalBlob],
  'price' : bigint,
}
export type ProductCategory = { 'other' : null } |
  { 'home' : null } |
  { 'beauty' : null } |
  { 'books' : null } |
  { 'sports' : null } |
  { 'fashion' : null } |
  { 'electronics' : null };
export interface ProductOrderItem {
  'name' : string,
  'productId' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCustomerOffer' : ActorMethod<[CustomerOffer], undefined>,
  'createFounderOffer' : ActorMethod<[FounderOffer], undefined>,
  'createProduct' : ActorMethod<[Product], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllOffers' : ActorMethod<
    [],
    {
      'founderOffers' : Array<FounderOffer>,
      'customerOffers' : Array<CustomerOffer>,
    }
  >,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAppSettings' : ActorMethod<[], AppSettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[Principal], Array<CartItem>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAppSettings' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Order], undefined>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateAppName' : ActorMethod<[string], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];